### ISSUE TITLE
Error while using the Google collab : cannot import name 'DeepSpeedPlugin' from 'pytorch_lightning.plugins'

### ISSUE THREAD

**Issue by Fqlox** [minimaxir/aitextgen#215]
I tried both google collab (train from scratch or finetune with GPT-NEO) both have an issue while loading the module and gives : 
`cannot import name 'DeepSpeedPlugin' from 'pytorch_lightning.plugins'` (on the first cell while importing aitextgen)

I tried do uninstall and reinstall libraries as mentioned [here](https://github.com/minimaxir/aitextgen/issues/200#issuecomment-1339980281). But it did not do the trick.

Is there a workaround ?

Thanks in advance.

**Comment by JosephTico** [comment]
Having same issue

**Comment by rgxb2807** [comment]
Having the same issue but locally (Ubuntu 22.04 )

**Comment by aotra** [comment]
Have the exact same issue on collab

**Comment by mpsparrow** [comment]
Haven't fully tested it, but reverting to a previous version of `pytorch-lightning` like version 1.7.7 may be a workaround.
```
pip uninstall pytorch-lightning
pip install pytorch-lightning==1.7.7
```

**Comment by analyticray** [comment]
I tried pip uninstall pytorch-lightning
pip install pytorch-lightning==1.9.4

and also
pip install git+https://github.com/minimaxir/aitextgen
pip install git+https://github.com/scorixear/aitextgen

but still same error

**Comment by analyticray** [comment]
Hi. Is there any solution to this?

**Comment by JosephTico** [comment]
Maybe it's related to 7bfbddb7169f9546bb3f66145eb7bf4ef3a50e99, a rollback to an earlier PyTorch-lightning around 1.3.0

**Comment by Fqlox** [comment]
> Maybe it's related to [7bfbddb](https://github.com/minimaxir/aitextgen/commit/7bfbddb7169f9546bb3f66145eb7bf4ef3a50e99), a rollback to an earlier PyTorch-lightning around 1.3.1


Tried installing 1.3.1 instead of 1.9.4 and got 

`ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/usr/local/lib/python3.9/dist-packages/torchmetrics/utilities/data.py)
`

**Comment by darrinh** [comment]
On Ubuntu 22.04 doing  pip install pytorch-lightning==1.9.4 got it working for me.

**Comment by darrinh** [comment]
I've tried various versions of the touch lib + aitext and none of them work as yet.

**Comment by analyticray** [comment]
I manage to resolve the error on the google colab by running this:

!pip install -qq pytorch-lightning==1.7.0 transformers==4.21.3 aitextgen==0.6.0 

Please do let me know if it also solves your issue on colab?

**Comment by Fqlox** [comment]
> I manage to resolve the error on the google colab by running this:
> 
> !pip install -qq pytorch-lightning==1.7.0 transformers==4.21.3 aitextgen==0.6.0
> 
> Please do let me know if it also solves your issue on colab?

It works fine in both colab and local (CPU) for me,

Thanks

**Comment by darrinh** [comment]
What distro are you using?

Thanks
Darrin

**Comment by Veritas83** [comment]
```pip install -qq pytorch-lightning==1.7.0``` made it work for me on Win10 x64 Py 3.11

**Comment by darrinh** [comment]
Thanks [Veritas83](https://github.com/Veritas83)

> `pip install -qq pytorch-lightning==1.7.0` made it work for me on Win10 x64 Py 3.11

Thanks, that combo doesn't work with python 3.8.10, which is default for ubuntu 22.04, so I need to try an newer version of python.

**Comment by Endymi0nn** [comment]
> On Ubuntu 22.04 doing pip install pytorch-lightning==1.7.0 got it working for me with the demo. Trying to use the training example gives:
> 
> pytorch_lightning.utilities.exceptions.MisconfigurationException: The provided lr scheduler `LambdaLR` doesn't follow PyTorch's LRScheduler API. You should override the `LightningModule.lr_scheduler_step` hook with your own logic if you are using a custom LR scheduler.

i am getting the same error while training, found any fix ?

**Comment by anpoddubny** [comment]
Same issue with me (Python 3.10.8, Mac OS,  pip install pytorch-lightning==1.7.0 ). Error with training 
> The provided lr scheduler LambdaLR doesn't follow PyTorch's LRScheduler API

**Comment by ViCtOr-dev13** [comment]
try this : 
#!pip install -q aitextgen

!pip install git+https://github.com/scorixear/aitextgen

#!pip uninstall pytorch-lightning
!pip install pytorch-lightning==1.9.4

**Comment by huyremy** [comment]
it'

> try this : #!pip install -q aitextgen
> 
> !pip install git+https://github.com/scorixear/aitextgen
> 
> #!pip uninstall pytorch-lightning !pip install pytorch-lightning==1.9.4

it's work but I get this error:
ModuleNotFoundError: No module named 'transformers.models.cpmant.configuration_cpmant'. Can you help me ? I think due to version of transformerr.

**Comment by atoqed-1** [comment]
I've tried the various suggestions here, and none of them work with both **_generation and fine tuning_**.

With this setup:
```
python 3.11 - Windows 64bit
torch == 2.0.1
pytorch-lightning == 2.0.6
```

You get this error for both text generation and fine tuning:
```ImportError: cannot import name 'DeepSpeedPlugin' from 'pytorch_lightning.plugins'```

Downgrading pytorch-lightning to 1.9.4 gives this error:
```
ImportError: cannot import name '_TPU_AVAILABLE' from 'pytorch_lightning.utilities'
```

I've chased these errors and have had a case where text generation works (though I unfortunately lost that particular combination of packages), but fine tuning failed. I'm in need of fine tuning so this isn't good for my use case.

The [requirements file](https://github.com/minimaxir/aitextgen/blob/master/requirements.txt) suggests that a wide range of package versions will support the package, but it seems more apparent that a narrow version of packages should be recommended.

Do we have any insight into what exact package/python versions allows both text generation and fine tuning to work?

**Comment by UESTCSober** [comment]
> try this : #!pip install -q aitextgen
> 
> !pip install git+https://github.com/scorixear/aitextgen
> 
> #!pip uninstall pytorch-lightning !pip install pytorch-lightning==1.9.4

1.9.4 really works

**Comment by francescoboc** [comment]
I have the same problem. Tried all solutions proposed, none of them work.

**Comment by WarpedWartWars** [comment]
i know this issue is over a year old, but i decided to find the package versions that cause this and similar import-time problems. and thus, i found this configuration:
***
`import aitextgen` tested on python 3.13.2 on windows 11 64bit with
* rust (for compiling `tokenizers`)

and these python packages:
```
pip<24.1
aitextgen==0.6.0
pytorch-lightning<1.8.0
transformers>=4.34.0,<4.40.0
torchmetrics<1.0.0
```
notes:
* pip<24.1 is due to
```
DEPRECATION: pytorch-lightning 1.7.7 has a non-standard dependency specifier torch>=1.9.*. pip 24.1 will enforce this behaviour change.
```
* `transformers` 4.40.0 requires `tokenizers` 1.19.x, which fails to build on python 3.13, due to
```
error: the configured Python interpreter version (3.13) is newer than PyO3's maximum supported version (3.12)
= help: please check if an updated version of PyO3 is available. Current version: 0.21.2
```
***
i haven't tested anything other than just importing the package, but at least that works

i haven't checked with scorixear's fork yet, but i will at some point
